### ISSUE TITLE
Website defaced by porn content

### ISSUE THREAD

**Issue by jesuswasrasta** [meltmedia/notconf#2]
I see that http://www.notconf.com/index.php shows porn content 😲

**Comment by lynnandtonic** [comment]
Oh no! Not sure there’s anything that can be done about what’s being served at the domain since I’m assuming meltmedia doesn’t own it anymore.

@mmoulton @ctrimble Could you remove the domain / URLs from the About this repo and in the README?

**Comment by ctrimble** [comment]
@lynnandtonic I have removed the speaker submission link and the URL from the about section of the repo.

**Comment by lynnandtonic** [comment]
Thanks so much @ctrimble! This can probably be closed. 💃
